### ISSUE TITLE
福利 | 分享几个强大且好用的电影网站

### ISSUE THREAD

**Issue by byodian** [byodian/awesometools#17]
![ &#31119;&#21033; | &#20998;&#20139;&#20960;&#20010;&#24378;&#22823;&#19988;&#22909;&#29992;&#30340;&#30005;&#24433;&#32593;&#31449;]( https://ift.tt/eA8V8J)<br>
** &#24179;&#26102;&#27809;&#20107;&#30340;&#26102;&#20505;&#21916;&#27426;&#30475;&#20010;&#30005;&#24433;&#65292;&#20294;&#21448;&#19981;&#24819;&#24525;&#21463;&#21508;&#22823;&#20027;&#27969;&#35270;&#39057;&#32593;&#31449;&#37027;&#20123;&#34394;&#26631;&#30340;&#28165;&#26224;&#24230;&#65288;&#20182;&#20204;&#30340; 4K &#35270;&#39057;&#33021;&#26377; YouTube &#30340; 1080P &#28165;&#26224;&#23601;&#19981;&#38169;&#20102;&#65289;&#65292;&#25152;&#20197;&#25105;&#32463;&#24120;&#33258;&#24049;&#21435;&#25214;&#36164;&#28304;&#19979;&#36733;&#35266;&#30475;&#12290;&#26085;&#31215;&#26376;&#32047;&#65292;&#25105;&#20063;&#23601;&#25910;&#34255;&#20102;&#20960;&#20010;&#24378;&#22823;&#22909;&#29992;&#30340;&#24433;&#35270;&#32593;&#31449;&#65292;**<br>
**Tags**: &#22312;&#32447;&#32593;&#31449;<br>
via Pocket https://ift.tt/2CaJCr6<br>
October 12, 2018 at 12:16PM

**Comment by youwen21** [comment]
看想什么上这个网站直接搜索， yszx11.top ， 基本全网的短剧，电影都能搜索到，直接看。
